export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_REDIRECT_MODAL = 'FETCH_REDIRECT_MODAL';
export const FETCH_LASLO_MODAL = 'FETCH_LASLO_MODAL';
