export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_REDIRECT_MODAL = 'FETCH_REDIRECT_MODAL';
export const CLOSE_REDIRECT_MODAL = 'CLOSE_REDIRECT_MODAL';
export const FETCH_NEDELOV_MODAL = 'FETCH_NEDELOV_MODAL';
export const CLOSE_NEDELOV_MODAL = 'CLOSE_NEDELOV_MODAL';
